config/routes.rb
NwkmExpenser::Application.routes.draw do
  resources :users, only: [:show, :edit, :update]
  resources :sessions, only: [:new, :create, :destroy]
  resources :tags, except: :show
  resources :accounts
  resources :contacts
  resources :transactions
  resources :transfers, only: [:new, :create]

  root to: 'static_pages#home'

  match '/assets/expense_report_data_pie',  to: 'javascripts#expense_report_data_pie'
  match '/assets/expense_report_data_bar',  to: 'javascripts#expense_report_data_bar'

  match '/login',  to: 'sessions#new'
  match '/logout', to: 'sessions#destroy'

  get ':controller(/:action(/:nav))'
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_filter :signed_in_user

  add_breadcrumb "Transactions", :transactions_path

  def index
    fetch_transactions

    @total = @transactions.total_entries
  end

  def show
    fetch_transaction

    add_breadcrumb 'Transaction', @transaction
  end

  def new
    @transaction = Transaction.new
    @transfer = Transfer.new
    fetch_all_for_form

    add_breadcrumb "New", new_transaction_path
  end

  def create
    @transaction = Transaction.new(params[:transaction])
    @transfer = Transfer.new(params[:transfer])
    fetch_all_for_form

    add_breadcrumb "New", new_transaction_path

    if @transaction.save
      flash[:success] = t(:transaction_created)
      redirect_to transactions_path
    else
      render 'new'
    end
  end

  def edit
    fetch_transaction
    fetch_all_for_form

    add_breadcrumb 'Transaction', @transaction
    add_breadcrumb "Edit", edit_transaction_path(@transaction)
  end

  def update
    fetch_transaction
    fetch_all_for_form

    add_breadcrumb 'Transaction', @transaction
    add_breadcrumb "Edit", edit_transaction_path(@transaction)

    if @transaction.update_attributes(params[:transaction])
      flash[:success] = t(:transaction_updated)
      redirect_to transactions_path
    else
      render 'edit'
    end
  end

  def destroy
    fetch_transaction.destroy

    flash[:success] = t(:transaction_deleted)
    redirect_to transactions_url
  end

  private # ----------------------------------------------------------

  def fetch_transaction
    @transaction = Transaction.find(params[:id])
  end

  def fetch_transactions
    @transactions = Transaction.where('transaction_transfer_id IS NULL OR income = ?', :true).order('date DESC, created_at DESC').paginate(page: params[:page])
  end

  def fetch_all_for_form
    fetch_accounts
    fetch_contacts
    fetch_transactions_settlement
    fetch_tags
  end

  def fetch_accounts
    @accounts = Account.all
  end

  def fetch_contacts
    @contacts = Contact.all
  end

  def fetch_transactions_settlement
    @transactions_with_contact = Transaction.where('contact_id IS NOT NULL')
  end

  def fetch_tags
    @tags = Tag.all
  end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
  def transactions_between(start_date, end_date, income=false)
    transactions = Transaction.where(date: start_date..end_date)
                              .where('income = ?', income)
                              .includes(:tag)

    return transactions
  end

  def expenses_between(start_date, end_date)
    return transactions_between start_date, end_date, false
  end

  def incomes_between(start_date, end_date)
    return transactions_between start_date, end_date, true
  end

  def category_expense(transactions)
    categories = Graph::CategoryGraph.new

    transactions.each do |t|
      categories.add_transaction(t)
    end

    return categories
  end
end

app/views/transactions/_fields.html.erb
<%= render 'layouts/error_messages', resource: @transaction %>

<div class="control-group">
  <%= f.label :income, class: "control-label" %>
  <div class="controls">
    <%= f.select :income, {"Income" => true, "Expense" => false}, {}, {class: "chzn-select"} %>
  </div>
</div>

<div class="control-group">
  <%= f.label :account_id, class: "control-label" %>
  <div class="controls">
    <%= f.select :account_id, @accounts.collect { |account| [account.name, account.id] }, {include_blank: false}, {class: "chzn-select-deselect"} %>
  </div>
</div>

<div class="control-group">
  <%= f.label :tag_id, class: "control-label" %>
  <div class="controls">
    <%= f.select :tag_id, @tags.collect { |tag| [tag.full_name, tag.id] }, {include_blank: true}, {class: "chzn-select-deselect", 'data-placeholder' => 'Select a category'} %>
  </div>
</div>

<div class="control-group">
  <%= f.label :contact_id, class: "control-label" %>
  <div class="controls">
    <%= f.select :contact_id, @contacts.collect { |account| [account.name, account.id] }, {include_blank: true}, {class: "chzn-select-deselect", 'data-placeholder' => 'Select a contact'} %>
  </div>
</div>

<div class="control-group">
  <%= f.label :transaction_settlement_id, class: "control-label" %>
  <div class="controls">
    <%= f.select :transaction_settlement_id, @transactions_with_contact.collect { |transaction| [transaction.summary_string(include_date: true), transaction.id] }, {include_blank: true}, {class: "chzn-select-deselect", 'data-placeholder' => 'Select a transaction'} %>
  </div>
</div>

<div class="control-group">
  <%= f.label :description, class: "control-label" %>
  <div class="controls">
    <%= f.text_area :description, {placeholder: 'Short summary of the transaction', rows: 5} %>
  </div>
</div>

<div class="control-group">
  <%= f.label :amount_dollars, "Amount", class: "control-label" %>
  <div class="controls">
    <%= f.number_field :amount_dollars, {step: 0.01} %>
  </div>
</div>

<div class="control-group">
  <%= f.label :date, class: "control-label" %>
  <div class="controls">
    <span class="input-icon input-icon-right">
      <%= f.text_field :date, class: "date-picker", 'data-date-format' => "yyyy-mm-dd", placeholder: 'Select a date' %>
      <i class="icon-calendar"></i>
    </span>
  </div>
</div>

app/views/transactions/_fields_transfer.html.erb
<%= render 'layouts/error_messages', resource: @transfer %>

<div class="control-group">
  <%= f.label :account_to_id, class: "control-label" %>
  <div class="controls">
    <%= f.select :account_to_id, @accounts.collect { |account| [account.name, account.id] }, {include_blank: false}, {class: "chzn-select-deselect"} %>
  </div>
</div>

<div class="control-group">
  <%= f.label :account_from_id, class: "control-label" %>
  <div class="controls">
    <%= f.select :account_from_id, @accounts.collect { |account| [account.name, account.id] }, {include_blank: false}, {class: "chzn-select-deselect"} %>
  </div>
</div>

<div class="control-group">
  <%= f.label :description, class: "control-label" %>
  <div class="controls">
    <%= f.text_area :description, {placeholder: 'Short summary of the transaction', rows: 5} %>
  </div>
</div>

<div class="control-group">
  <%= f.label :amount_dollars, "Amount", class: "control-label" %>
  <div class="controls">
    <%= f.number_field :amount_dollars, {step: 0.01} %>
  </div>
</div>

<div class="control-group">
  <%= f.label :date, class: "control-label" %>
  <div class="controls">
    <span class="input-icon input-icon-right">
      <%= f.text_field :date, class: "date-picker", 'data-date-format' => "yyyy-mm-dd", placeholder: 'Select a date' %>
      <i class="icon-calendar"></i>
    </span>
  </div>
</div>

app/views/transactions/_transaction.html.erb
<tr>
  <td><%= link_to transaction.description, transaction %></td>
  <td><%= transaction.icon_html %> <%= number_to_currency transaction.amount_dollars %></td>
  <td><%= raw transaction.tag_html %></td>
  <td>
    <%= link_to transaction.account.name, account_path(transaction.account) %>
    <%= transaction.transfer_to? ? raw(' <i class="icon-arrow-right purple"></i> ') + link_to(transaction.corresponding_expense.account.name, account_path(transaction.corresponding_expense.account)) : '' %>
  </td>
  <td><%= l transaction.date, format: :long %></td>
  <td><%= transaction.paid_on_behalf? ? link_to(transaction.paid_on_behalf.name, contact_path(transaction.paid_on_behalf)) : '' %></td>
  <td><%= transaction.settles? ? link_to(transaction.settles.summary_string(format: :short), transaction_path(transaction.settles)) : '' %></td>
  <td>
    <%= link_to raw('<i class="icon-edit icon-white"></i> Edit'), edit_transaction_path(transaction), {class: "btn btn-small btn-warning"} %>
    <%= link_to raw('<i class="icon-trash icon-white"></i> Delete'), transaction, class: "btn btn-small btn-danger", method: :delete, data: { confirm: t(:confirm_transaction_delete, {id: transaction.id, type: transaction.income_string, description: transaction.description, amount: transaction.amount, date: transaction.date})} %></td>
</tr>

app/views/transactions/edit.html.erb
<% provide(:title, 'Transaction') %> 
<% provide(:titleSmall, 'Edit') %>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@transaction, html: {class: "form-horizontal"}) do |f| %>
      
      <%=render 'fields', f: f %>

      <div class="form-actions">
        <%= button_tag(type: :submit, class: "btn btn-small btn-success") do %>
          <i class='icon-ok'></i> Save changes
        <% end %>
        <%= link_to raw("<i class='icon-remove'></i> Cancel"), transactions_path, class: "btn btn-small" %>
      </div>
    <% end %>
  </div>
</div>

<% provide :leftNavButtonBody, 'Transactions' %>
<% provide :leftNavButtonUrl, transactions_path %>

app/views/transactions/index.html.erb
<% provide(:title, 'Transactions') %>
<% provide(:titleSmall, 'All') %>

<% provide :actions, link_to(raw('<i class="icon-plus icon-white"></i> New Transaction'), new_transaction_path, class: "btn btn-small btn-primary") %>

<%= render 'layouts/pagination' %>

<table class="table table-striped table-bordered table-hover">
  <tr>
    <th>Description</th>
    <th>Amount</th>
    <th>Tags</th>
    <th>Account</th>
    <th>Date</th>
    <th>Paid on Behalf</th>
    <th>Settlement</th>
    <th></th>
  </tr>

  <%=render @transactions %>

</table>

<%= render 'layouts/pagination' %>

<% provide :leftNavButtonBody, 'Home' %>
<% provide :leftNavButtonUrl, root_path %>

app/views/transactions/new.html.erb
<% provide(:title, 'Transaction') %>
<% provide(:titleSmall, 'New') %>

<div class="row-fluid">
  <div class="tabbable">
    <ul id="myTab" class="nav nav-tabs">
      <li class="active">
        <a data-toggle="tab" href="#transaction">
          <i class="icon-credit-card bigger-110"></i> Transaction
        </a>
      </li>
      <li>
        <a data-toggle="tab" href="#transfer">
          <i class="icon-exchange bigger-110"></i> Transfer
        </a>
      </li>
    </ul>

    <div class="tab-content">
      <div id="transaction" class="tab-pane in active">
        <%= form_for(@transaction, html: {class: "form-horizontal"}) do |f| %>
          <%=render 'transactions/fields', f: f %>
          <div class="form-actions">
            <%= button_tag(type: :submit, class: "btn btn-small btn-success") do %>
              <i class='icon-ok'></i> Create Transaction
            <% end %>
            <%= link_to raw("<i class='icon-remove'></i> Cancel"), transactions_path, class: "btn btn-small" %>
          </div>
        <% end %>
      </div>

      <div id="transfer" class="tab-pane">
        <%= form_for(@transfer, html: {class: "form-horizontal"}, url: '/transfers#transfer') do |f| %>
          <%=render 'transactions/fields_transfer', f: f %>
          <div class="form-actions">
            <%= button_tag(type: :submit, class: "btn btn-small btn-success") do %>
              <i class='icon-ok'></i> Create Transaction
            <% end %>
            <%= link_to raw("<i class='icon-remove'></i> Cancel"), transactions_path, class: "btn btn-small" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/transactions/show.html.erb
<% provide(:title, 'Transaction') %>
<% provide(:titleSmall, 'View') %>

<div class="row-fluid">
  <dl class="dl-horizontal">
    <%= dtdd 'Date', l(@transaction.date, format: :long) %>
    <%= dtdd 'Type', @transaction.income_string %>
    <%= dtdd 'Account', link_to(@transaction.account.name, account_path(@transaction.account)) %>
    <%= dtdd 'Amount', @transaction.amount_dollars %>
    <%= dtdd 'Description', @transaction.description %>
    <%= dtdd 'Category', raw(@transaction.tag_html) %>
    <%= dtdd '', link_to(raw("<i class='icon-edit'></i> Edit"), edit_transaction_path(@transaction), class: "btn btn-small btn-warning") %>
  </dl>
</div>