config/routes.rb
NwkmExpenser::Application.routes.draw do
  resources :users, only: [:show, :edit, :update]
  resources :sessions, only: [:new, :create, :destroy]
  resources :tags, except: :show
  resources :accounts
  resources :contacts
  resources :transactions
  resources :transfers, only: [:new, :create]

  root to: 'static_pages#home'

  match '/assets/expense_report_data_pie',  to: 'javascripts#expense_report_data_pie'
  match '/assets/expense_report_data_bar',  to: 'javascripts#expense_report_data_bar'

  match '/login',  to: 'sessions#new'
  match '/logout', to: 'sessions#destroy'

  get ':controller(/:action(/:nav))'
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  include TransactionsHelper

  before_filter :signed_in_user

  add_breadcrumb "Reports", '/reports'

  def expense
    process_dates
    fetch_transactions

    add_breadcrumb "Expense", '/reports/expense'

    @permitted_params = ['date_start', 'date_end']
  end

  private #---------------------------------------

  def fetch_transactions
    @transactions = expenses_between params[:date_start], params[:date_end]
  end

  def process_dates
    unless params[:nav].nil?
      case params[:nav]
      when 'month'
        params[:date_start] = Date.today.beginning_of_month
        params[:date_end]   = Date.today.end_of_month
      when 'month_last'
        params[:date_start] = Date.today.ago(1.month).beginning_of_month
        params[:date_end]   = Date.today.ago(1.month).end_of_month
      when 'month_last_3'
        params[:date_start] = Date.today.ago(2.month).beginning_of_month
        params[:date_end]   = Date.today.end_of_month
      when 'year'
        params[:date_start] = Date.today.beginning_of_year
        params[:date_end]   = Date.today.end_of_year
      when 'year_last'
        params[:date_start] = Date.today.ago(1.year).beginning_of_year
        params[:date_end]   = Date.today.ago(1.year).end_of_year
      when 'custom'

      else

      end
    end
  end
end

app/views/reports/_nav_pills.html.erb
<div class="row-fluid">
  <div class="span6">
    <ul class="nav nav-pills">
      <li class="<%= navbar_active_pill 'month' %>">
        <a href="/reports/expense/month">This Month</a>
      </li>
      <li class="<%= navbar_active_pill 'month_last' %>">
        <a href="/reports/expense/month_last">Last Month</a>
      </li>
      <li class="<%= navbar_active_pill 'month_last_3' %>">
        <a href="/reports/expense/month_last_3">Last 3 Months</a>
      </li>
      <li class="<%= navbar_active_pill 'year' %>">
        <a href="/reports/expense/year">This Year</a>
      </li>
      <li class="<%= navbar_active_pill 'year_last' %>">
        <a href="/reports/expense/year_last">Last Year</a>
      </li>
      <li class="<%= navbar_active_pill 'custom' %>">
        <a href="/reports/expense/custom">Custom</a>
      </li>
    </ul>
  </div>
</div>

app/views/reports/expense.html.erb
<% provide(:title, 'Expenses') %>
<% provide(:titleSmall, 'Report') %>

<% javascript_with_params(javascript_path('expense_report_data_pie') + '?' + params.select{|k| @permitted_params.include?(k)}.to_query) %>
<% javascript_with_params(javascript_path('expense_report_data_bar') + '?' + params.select{|k| @permitted_params.include?(k)}.to_query) %>

<%= render 'nav_pills' %>

<% if params[:nav] == 'custom' && (params[:date_start].nil? || params[:date_end].nil?) %>
  
  <!-- form for selecting start and end dates -->
  <div class="row-fluid">
    <%= form_tag '', method: :get, class: "form-horizontal" %>
      
      <div class="control-group">
        <%= label_tag :date_start, 'Start Date', class: "control-label" %>
        <div class="controls">
          <span class="input-icon input-icon-right">
            <%= text_field_tag :date_start, '', class: "date-picker", 'data-date-format' => "yyyy-mm-dd", placeholder: 'Select a date' %>
            <i class="icon-calendar"></i>
          </span>
        </div>
      </div>

      <div class="control-group">
        <%= label_tag :date_end, 'End Date', class: "control-label" %>
        <div class="controls">
          <span class="input-icon input-icon-right">
            <%= text_field_tag :date_end, '', class: "date-picker", 'data-date-format' => "yyyy-mm-dd", placeholder: 'Select a date' %>
            <i class="icon-calendar"></i>
          </span>
        </div>
      </div>

      <div class="form-actions">
        <%= button_tag(type: :submit, class: "btn btn-small btn-success") do %>
          <i class='icon-ok'></i> Create Report
        <% end %>
      </div>
  </div>

<% else %>

  <div class="row-fluid">
    <h4 class="center">
      <div id="total-placeholder">

      </div>
    </h4>
    <hr>
  </div>


  <div class="row-fluid">
    <div class="span3"></div>
    <div class="span6">
      <div id="piechart-placeholder" style="width:100%; min-height:350px;"></div>
    </div>
    <div class="span3"></div>
  </div>

  <div class="row-fluid">
    <div class="span3"></div>
    <div class="span6">
      <div id="barchart-placeholder" style="width:100%; min-height:350px;"></div>
    </div>
    <div class="span3"></div>
  </div>

  <div class="row-fluid">
    
  </div>

<% end %>