config/routes.rb
NwkmExpenser::Application.routes.draw do
  resources :users, only: [:show, :edit, :update]
  resources :sessions, only: [:new, :create, :destroy]
  resources :tags, except: :show
  resources :accounts
  resources :contacts
  resources :transactions
  resources :transfers, only: [:new, :create]

  root to: 'static_pages#home'

  match '/assets/expense_report_data_pie',  to: 'javascripts#expense_report_data_pie'
  match '/assets/expense_report_data_bar',  to: 'javascripts#expense_report_data_bar'

  match '/login',  to: 'sessions#new'
  match '/logout', to: 'sessions#destroy'

  get ':controller(/:action(/:nav))'
end

app/views/layouts/_breadcrumbs.html.erb
<div id="breadcrumbs">
  <%= render_breadcrumbs raw('<i class="icon-angle-right"></i>') %>
  <div id="nav-search">
    <form class="form-search">
      <span class="input-icon">
        <input type="text" placeholder="Search ..." class="input-small search-query" id="nav-search-input" autocomplete="off">
        <i class="icon-search" id="nav-search-icon"></i>
      </span>
    </form>
  </div>
</div>

app/views/layouts/_debug.html.erb
<div class="row-fluid">
  <%= debug(params) if Rails.env.development? %>
</div>

app/views/layouts/_error_messages.html.erb
<% if !resource.nil? && resource.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(resource.errors.count, "error") %>.
    </div>
    <ul>
    <% resource.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer id="footer" class="footer">
  <div class="container">
    
  </div>
</footer>

app/views/layouts/_footer_nav.html.erb
<div class="container nwkm_navButtons nwkm_navButtonsFooter">
  <div class="row">
    <div class="span4">
      <% if content_for? :leftNav %>
        <%= yield :leftNav %>
      <% elsif content_for?(:leftNavButtonBody) && content_for?(:leftNavButtonUrl) %>
        <%= link_to(raw("<i class='icon-circle-arrow-left'></i> #{yield(:leftNavButtonBody)}"), yield(:leftNavButtonUrl), class: "btn pull-left") %>
      <% else %>
        &nbsp;
      <% end %>
    </div>

    <div class="span2 offset1">
      <% if content_for? :centerNav %>
        <%= yield :centerNav %>
      <% elsif content_for?(:centerNavButtonBody) && content_for?(:centerNavButtonUrl) %>
        <%= link_to(raw("#{yield(:centerNavButtonBody)}"), yield(:centerNavButtonUrl), class: "btn btn-large") %>
      <% else %>
        &nbsp;
      <% end %>
    </div>

    <div class="span4 offset1">
      <% if content_for? :rightNav %>
        <%= yield :rightNav %>
      <% elsif content_for?(:rightNavButtonBody) && content_for?(:rightNavButtonUrl) %>
        <%= link_to(raw("#{yield(:rightNavButtonBody)} <i class='icon-circle-arrow-right'></i>"), yield(:rightNavButtonUrl), class: "btn pull-right") %>
      <% else %>
        &nbsp;
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container-fluid">
      <a href="<%= root_path %>" class="brand">
        <small>
          <i class="icon-bar-chart"></i>
          Expenser
        </small>
      </a>

      <ul class="nav ace-nav pull-right">
        <% unless current_user.nil? %>
          <li class="light-blue user-profile">
            <a data-toggle="dropdown" href="#" class="user-menu dropdown-toggle">
              <i class="icon-cog"></i>
              <span id="user_info">
                <small>Welcome,</small><%= current_user.first_name %>
              </span>
              <i class="icon-caret-down"></i>
            </a>

            <ul class="pull-right dropdown-menu dropdown-yellow dropdown-caret dropdown-closer" id="user_menu">
              <li>
                <%= link_to raw('<i class="icon-user"></i> Profile'),  current_user %>
              </li>
              <li>
                <%= link_to raw('<i class="icon-wrench"></i> Settings'), edit_user_path(current_user) %>
              </li>

              <li class="divider"></li>

              <li>
                <%= link_to raw('<i class="icon-off"></i> Sign Out'), logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% end %>
      </ul><!--/.ace-nav-->
    </div><!--/.container-fluid-->
  </div><!--/.navbar-inner-->
</div>

app/views/layouts/_header_page.html.erb
<div class="page-header position-relative">
  <% if content_for? :title %>
    <h1>
      <%= yield :title %>
      <% if content_for? :titleSmall %>
        <i class="icon-double-angle-right"></i>
        <small>
          <%= yield :titleSmall %>
        </small>
      <% end %>
    </h1>
  <% else %>
    <h1>
      Page has no title
      <i class="icon-double-angle-right"></i>
        <small>
          Maybe make one?
        </small>
    </h1>
  <% end %>
</div>

app/views/layouts/_pagination.html.erb
<div class="nwkm_actionsPagination row-fluid">
  <div class="nwkm_actions span5">
    <%= yield :actions %>
  </div>
  <% unless @total.nil? %>
    <div class="nwkm_paginationTotal span2">
      <%= pluralize @total, 'result' %> found
    </div>
    <div class="nwkm_pagination span5">
      <%= will_paginate %>
    </div>
  <% end %>
</div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/_sidebar.html.erb
<a id="menu-toggler" href="#" class="">
  <span></span>
</a>
<div id="sidebar" class="fixed">
  <div id="sidebar-shortcuts">
    <div id="sidebar-shortcuts-large">
      <button class="btn btn-small btn-success">
        <i class="icon-signal"></i>
      </button>

      <button class="btn btn-small btn-info">
        <i class="icon-pencil"></i>
      </button>

      <button class="btn btn-small btn-warning">
        <i class="icon-group"></i>
      </button>

      <button class="btn btn-small btn-danger">
        <i class="icon-cogs"></i>
      </button>
    </div>

    <div id="sidebar-shortcuts-mini">
      <span class="btn btn-success"></span>

      <span class="btn btn-info"></span>

      <span class="btn btn-warning"></span>

      <span class="btn btn-danger"></span>
    </div>
  </div><!--#sidebar-shortcuts-->

  <ul class="nav nav-list">
    <!-- Accounts -->
    <li class="<%= sidebar_active_controller 'accounts' %>">
      <a href="#" class="dropdown-toggle">
        <i class="icon-money"></i>
        <span>Accounts</span>
        <b class="arrow icon-angle-down"></b>
      </a>

      <ul class="submenu">
        <li class="<%= sidebar_active_view 'accounts', 'index' %>">
          <%= link_to raw('<i class="icon-double-angle-right"></i> View'), accounts_path %>
        </li>
        <li class="<%= sidebar_active_view 'accounts', 'new' %>">
          <%= link_to raw('<i class="icon-double-angle-right"></i> Create'), new_account_path %>
        </li>
      </ul>
    </li>

    <!-- Tags -->
    <li class="<%= sidebar_active_controller 'tags' %>">
      <a href="#" class="dropdown-toggle">
        <i class="icon-tag"></i>
        <span>Tags</span>
        <b class="arrow icon-angle-down"></b>
      </a>

      <ul class="submenu">
        <li class="<%= sidebar_active_view 'tags', 'index' %>">
          <%= link_to raw('<i class="icon-double-angle-right"></i> View'), tags_path %>
        </li>
        <li class="<%= sidebar_active_view 'tags', 'new' %>">
          <%= link_to raw('<i class="icon-double-angle-right"></i> Create'), new_tag_path %>
        </li>
      </ul>
    </li>

    <!-- Contacts -->
    <li class="<%= sidebar_active_controller 'contacts' %>">
      <a href="#" class="dropdown-toggle">
        <i class="icon-user"></i>
        <span>Contacts</span>
        <b class="arrow icon-angle-down"></b>
      </a>

      <ul class="submenu">
        <li class="<%= sidebar_active_view 'contacts', 'index' %>">
          <%= link_to raw('<i class="icon-double-angle-right"></i> View'), contacts_path %>
        </li>
        <li class="<%= sidebar_active_view 'contacts', 'new' %>">
          <%= link_to raw('<i class="icon-double-angle-right"></i> Create'), new_contact_path %>
        </li>
      </ul>
    </li>

    <!-- Transactions -->
    <li class="<%= sidebar_active_controller 'transactions' %>">
      <a href="#" class="dropdown-toggle">
        <i class="icon-credit-card"></i>
        <span>Transactions</span>
        <b class="arrow icon-angle-down"></b>
      </a>

      <ul class="submenu">
        <li class="<%= sidebar_active_view 'transactions', 'index' %>">
          <%= link_to raw('<i class="icon-double-angle-right"></i> View'), transactions_path %>
        </li>
        <li class="<%= sidebar_active_view 'transactions', 'new' %>">
          <%= link_to raw('<i class="icon-double-angle-right"></i> Create'), new_transaction_path %>
        </li>
      </ul>
    </li>

    <!-- Transactions -->
    <li class="<%= sidebar_active_controller 'reports' %>">
      <a href="#" class="dropdown-toggle">
        <i class="icon-signal"></i>
        <span>Reports</span>
        <b class="arrow icon-angle-down"></b>
      </a>

      <ul class="submenu">
        <li class="<%= sidebar_active_view 'reports', '' %>">
          <%= link_to raw('<i class="icon-double-angle-right"></i> Summary'), '/reports/' %>
        </li>
        <li class="<%= sidebar_active_view 'reports', 'income' %>">
          <%= link_to raw('<i class="icon-double-angle-right"></i> Income'), '/reports/income' %>
        </li>
        <li class="<%= sidebar_active_view 'reports', 'expense' %>">
          <%= link_to raw('<i class="icon-double-angle-right"></i> Expense'), '/reports/expense' %>
        </li>
        <li class="<%= sidebar_active_view 'reports', 'balance' %>">
          <%= link_to raw('<i class="icon-double-angle-right"></i> Balance'), '/reports/balance' %>
        </li>
      </ul>
    </li>
  </ul><!--/.nav-list-->

  <div id="sidebar-collapse">
    <i class="icon-double-angle-left"></i>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%=fullTitle(yield(:title)) %></title>
  <%= stylesheet_link_tag "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= yield :head %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
  <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Open+Sans:400,300" />
</head>
<body class="navbar-fixed">
  <%= render 'layouts/header' %>
  <div id="main-container" class="container-fluid">
    <%= render 'layouts/sidebar' %>
    <div id="main-content" class="clearfix">
      <%= render 'layouts/breadcrumbs' %>
      <div id="page-content" class="clearfix">
        <%= render 'layouts/header_page' %>
        <% flash.each do |key, value| %>
          <%= content_tag(:div, value, class: "alert alert-#{key}") %>
        <% end %>
        <%= yield %>
        <%= render 'layouts/footer' %>
        <!--<%= render 'layouts/debug' %>-->
      </div>
    </div>
  </div>
</body>
</html>

app/views/layouts/login.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%=fullTitle(yield(:title)) %></title>
  <%= stylesheet_link_tag "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
  <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Open+Sans:400,300" />
</head>
<body class="login-layout">
  <div class="container-fluid" id="main-container">
    <div id="main-content">
      <div class="row-fluid">
        <div class="span12">
          <div class="login-container">
            <div class="row-fluid">
              <div class="center">
                <h1>
                  <i class="icon-leaf green"></i>
                  <span class="red">Nwkm</span>
                  <span class="white">Expenser</span>
                </h1>
                <h4 class="blue">&copy; ninjawithkillmoon</h4>
              </div>
            </div>

            <div class="space-6"></div>

            <div class="row-fluid">
              <div class="position-relative">
                <div id="login-box" class="visible widget-box no-border">
                  <div class="widget-body">
                    <div class="widget-main">
                      <h4 class="header blue lighter bigger">
                        <i class="icon-signin green"></i>
                        Please Enter Your Information
                      </h4>

                      <div class="space-6"></div>
                      <% flash.each do |key, value| %>
                        <%= content_tag(:div, value, class: "alert alert-#{key}") %>
                      <% end %>
                      <%= yield %>
                    </div><!--/widget-main-->
                    <!--
                    <div class="toolbar clearfix">
                      <div>
                        <a href="#" onclick="show_box('forgot-box'); return false;" class="forgot-password-link">
                          <i class="icon-arrow-left"></i>
                          I forgot my password
                        </a>
                      </div>

                      <div>
                        <a href="#" onclick="show_box('signup-box'); return false;" class="user-signup-link">
                          I want to register
                          <i class="icon-arrow-right"></i>
                        </a>
                      </div>
                    </div>
                    -->
                  </div><!--/widget-body-->
                </div><!--/login-box-->
                <!--
                <div id="forgot-box" class="widget-box no-border">
                  <div class="widget-body">
                    <div class="widget-main">
                      <h4 class="header red lighter bigger">
                        <i class="icon-key"></i>
                        Retrieve Password
                      </h4>

                      <div class="space-6"></div>
                      <p>
                        Enter your email and to receive instructions
                      </p>

                      <form>
                        <fieldset>
                          <label>
                            <span class="block input-icon input-icon-right">
                              <input type="email" class="span12" placeholder="Email" />
                              <i class="icon-envelope"></i>
                            </span>
                          </label>

                          <div class="row-fluid">
                            <button onclick="return false;" class="span5 offset7 btn btn-small btn-danger">
                              <i class="icon-lightbulb"></i>
                              Send Me!
                            </button>
                          </div>
                        </fieldset>
                      </form>
                    </div>

                    <div class="toolbar center">
                      <a href="#" onclick="show_box('login-box'); return false;" class="back-to-login-link">
                        Back to login
                        <i class="icon-arrow-right"></i>
                      </a>
                    </div>
                  </div>
                </div>
                -->
                <!--
                <div id="signup-box" class="widget-box no-border">
                  <div class="widget-body">
                    <div class="widget-main">
                      <h4 class="header green lighter bigger">
                        <i class="icon-group blue"></i>
                        New User Registration
                      </h4>

                      <div class="space-6"></div>
                      <p>
                        Enter your details to begin:
                      </p>

                      <form>
                        <fieldset>
                          <label>
                            <span class="block input-icon input-icon-right">
                              <input type="email" class="span12" placeholder="Email" />
                              <i class="icon-envelope"></i>
                            </span>
                          </label>

                          <label>
                            <span class="block input-icon input-icon-right">
                              <input type="text" class="span12" placeholder="Username" />
                              <i class="icon-user"></i>
                            </span>
                          </label>

                          <label>
                            <span class="block input-icon input-icon-right">
                              <input type="password" class="span12" placeholder="Password" />
                              <i class="icon-lock"></i>
                            </span>
                          </label>

                          <label>
                            <span class="block input-icon input-icon-right">
                              <input type="password" class="span12" placeholder="Repeat password" />
                              <i class="icon-retweet"></i>
                            </span>
                          </label>

                          <label>
                            <input type="checkbox" />
                            <span class="lbl">
                              I accept the
                              <a href="#">User Agreement</a>
                            </span>
                          </label>

                          <div class="space-24"></div>

                          <div class="row-fluid">
                            <button type="reset" class="span6 btn btn-small">
                              <i class="icon-refresh"></i>
                              Reset
                            </button>

                            <button onclick="return false;" class="span6 btn btn-small btn-success">
                              Register
                              <i class="icon-arrow-right icon-on-right"></i>
                            </button>
                          </div>
                        </fieldset>
                      </form>
                    </div>

                    <div class="toolbar center">
                      <a href="#" onclick="show_box('login-box'); return false;" class="back-to-login-link">
                        <i class="icon-arrow-left"></i>
                        Back to login
                      </a>
                    </div>
                  </div>
                </div>
                -->
              </div><!--/position-relative-->
            </div>
          </div>
        </div><!--/span-->
      </div><!--/row-->
    </div>
  </div><!--/.fluid-container-->

  <!--basic scripts-->
  <!--
  <script type="text/javascript">
    function show_box(id) {
     $('.widget-box.visible').removeClass('visible');
     $('#'+id).addClass('visible');
    }
  </script>
  -->
</body>
</html>